spring:
  application:
    name: ${APP_NAME:test-service}

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:https://www.pinjun.xyz/config}

eureka:
  instance:
    prefer-ip-address: false
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    ip-address: ${EUREKA_INSTANCE_HOSTNAME:localhost}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:https://www.pinjun.xyz/eureka1/eureka/,https://www.pinjun.xyz/eureka2/eureka/}

server:
  port: ${SERVER_PORT:8097}